### ISSUE TITLE
thread panic occurred

### ISSUE THREAD

**Issue by SreeniIO** [HiRoFa/quickjs_es_runtime#69]
Program panics at times, when the string returned from js to rust contains emoji.

```
thread panic occurred: panicked at 'bad cstr bad!: Utf8Error { valid_up_to: 0, error_len: Some(1) }', .../.cargo/registry/src/github.com-1ecc6299db9ec823/quickjs_runtime-0.8.2/src/quickjs_utils/primitives.rs:116:22
```

Also when the JavaScript function returns the below JSON string with emoji. The string value returned back to rust contains random chars e.g. Atom('J' type=inline)

```
[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]
```

Code used to read the value in rust
```
JsValueFacade::String { val } => Ok(val.to_string()), // val contains J, Q, = etc... and causes the above panic at times.
```

But, if the return message is as below, then there is no issue!
```
[{"appUid":"cloudio","comment":"test","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:29:24.310918Z","lastUpdateDate":"2022-08-18T06:29:24.310918Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQT8TPP9N3HV4K1GXWCX509","_rs":"Q"},{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]
```

The returned value is Atom of type dymamic, whereas for the above the problem case the type is inline.
```
Atom('{"rows":[{"appUid":"cloudio","comment":"test","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:29:24.310918Z","lastUpdateDate":"2022-08-18T06:29:24.310918Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQT8TPP9N3HV4K1GXWCX509","_rs":"Q"},{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}' type=dynamic)
```

**Comment by SreeniIO** [comment]
Here is a repo with the sample code to reproduce the issue
https://github.com/SreeniIO/jstest2

**Comment by SreeniIO** [comment]
The return value changes based on where the emoji is in the return JSON string. e.g. `Atom('<' type=inline)` `Atom('J' type=inline)` `Atom('=' type=inline)`. 

If the returned value is just an emoji, it works.

**Comment by SreeniIO** [comment]
I'm able to reproduce the panic if I run the below code in loop. Also updated the sample repo with the below changes.

Sample code
```rust
for i in 0..10 {
        println!("\nloop {}\n", i);
        let rt = rt.clone();
        match rt.js_loop_realm_sync(Some(id), move |_q_js_rt, q_ctx| {
            let res = q_ctx.eval(Script::new(
                "test.js",
                r#"JSON.stringify({rows: [{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]})"#,
            ));

            match res {
                Ok(js) => q_ctx.to_js_value_facade(&js),
                Err(e) => Err(e),
            }
        }) {
            Ok(r) => {
                let fut = get_as_string(rt, r, "return value".to_owned(), id.to_string()).await;
                match fut {
                    Ok(val) => println!("result={}", val),
                    Err(e) => eprintln!("err: {}", e),
                };
            }
            Err(e) => {
                eprintln!("error: {}", e);
            }
        };
    }
```

Output

```
loop 0

val=Atom('>' type=inline)
string val=>
result=>

loop 1

val=Atom('?' type=inline)
string val=?
result=?

loop 2

val=Atom('?' type=inline)
string val=?
result=?

loop 3

thread panic occurred: panicked at 'bad cstr bad!: Utf8Error { valid_up_to: 0, error_len: None }', /Users/sthamman/.cargo/registry/src/github.com-1ecc6299db9ec823/quickjs_runtime-0.8.2/src/quickjs_utils/primitives.rs:116:22

```

**Comment by andrieshiemstra** [comment]
On my linux box i get
```
loop 0

val=Atom('{"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}' type=dynamic)
string val={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}
result={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}

loop 1

val=Atom('{"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}' type=dynamic)
string val={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}
result={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}

loop 2

val=Atom('{"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}' type=dynamic)
string val={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}
result={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}

loop 3

val=Atom('{"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}' type=dynamic)
string val={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}
result={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}

loop 4

val=Atom('{"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}' type=dynamic)
string val={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}
result={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}

loop 5

val=Atom('{"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}' type=dynamic)
string val={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}
result={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}

loop 6

val=Atom('{"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}' type=dynamic)
string val={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}
result={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}

loop 7

val=Atom('{"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}' type=dynamic)
string val={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}
result={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}

loop 8

val=Atom('{"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}' type=dynamic)
string val={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}
result={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}

loop 9

val=Atom('{"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}' type=dynamic)
string val={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}
result={"rows":[{"appUid":"cloudio","comment":"👍","commentedBy":"admin","contextId":"$DD$","contextValue":"cloudio.home","createdBy":"admin","creationDate":"2022-08-18T06:17:06.871617Z","lastUpdateDate":"2022-08-18T06:17:06.871617Z","lastUpdatedBy":"admin","md":{},"orgUid":"cloudio","uid":"01GAQSJAHQ7WE54JNRC1J9HVH3","_rs":"Q"}]}
done
```

Do any of the testcases I added to primitives.rs fail on your machine?

**Comment by andrieshiemstra** [comment]
it may have something to do with how the DefaultAtom gets initialized in adapters.rs in utils on line 78
```rust
    val: DefaultAtom::from(js_value.js_to_str()?),
```

you could try changing that to 
```rust
    val: DefaultAtom::from(js_value.js_to_string()?),
```
so it gets initialized with an owned string 

If you cannot test that than I'll change it myself so you can test later... let me know

**Comment by SreeniIO** [comment]
That fixed it. Raised a PR. Might be something to do with multi cores. I've 10 cores on my mac.
